apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agc-utils
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # ── ArgoCD Image Updater ───────────────────────────────────────────────────
    argocd-image-updater.argoproj.io/image-list: agc-utils=ghcr.io/anime-gaming-cafe/agc-utils:latest
    argocd-image-updater.argoproj.io/agc-utils.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/anime-gaming-cafe/agc-utils.git
    targetRevision: HEAD
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: agc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
