apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - pvc.yaml
  - pvc-images.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Image tag is managed by ArgoCD Image Updater.
# The updater commits newTag changes back to this file automatically.
images:
  - name: ghcr.io/anime-gaming-cafe/agc-utils
    newTag: latest
