apiVersion: v1
kind: Service
metadata:
  name: agc-utils
  namespace: agc
  labels:
    app: agc-utils
spec:
  selector:
    app: agc-utils
  ports:
    - name: web
      port: 8085
      targetPort: 8085
    - name: transcripts
      port: 80
      targetPort: 80
    - name: images
      port: 81
      targetPort: 81
